FROM rockylinux/rockylinux:9
RUN dnf install -y iputils freeipa-client wget jq nmap-ncat
RUN find /etc/systemd/system /usr/lib/systemd/system/{basic,multi-user,sysinit}.target.wants -type l -not -lname /dev/null -delete && systemctl mask systemd-logind.service
COPY rpm/cfengine.rpm /cfengine.rpm
COPY rpm/kaf_07.rpm /kaf_07.rpm
RUN dnf -y install /cfengine.rpm /kaf_07.rpm
COPY config/config-patch.json /var/cfengine/private/cf-scripts/promises/com.teragrep-kaf_07/config/config-patch.json
RUN jq -s '.[0] * .[1]' /var/cfengine/private/cf-scripts/promises/com.teragrep-kaf_07/config/config.json.example /var/cfengine/private/cf-scripts/promises/com.teragrep-kaf_07/config/config-patch.json > /var/cfengine/private/cf-scripts/promises/com.teragrep-kaf_07/config/config.json
COPY config/kaf_04/authorize.json /var/cfengine/private/cf-scripts/promises/com.teragrep-kaf_07/config/kaf_04/authorize.json
COPY config/kaf_05/credentials.json /var/cfengine/private/cf-scripts/promises/com.teragrep-kaf_07/config/kaf_05/credentials.json
COPY rpm/kaf_04.rpm /var/cfengine/private/cf-scripts/promises/com.teragrep-kaf_07/rpm/
COPY rpm/kaf_05.rpm /var/cfengine/private/cf-scripts/promises/com.teragrep-kaf_07/rpm/
COPY rpm/kaf_06.rpm /var/cfengine/private/cf-scripts/promises/com.teragrep-kaf_07/rpm/
COPY files/entrypoint.cluster.sh /entrypoint.sh
COPY files/entrypoint.service /etc/systemd/system/entrypoint.service
RUN systemctl enable entrypoint.service
ENTRYPOINT ["/usr/sbin/init"]
CMD ["--show-status=false"]
