FROM ghcr.io/teragrep/ipa_01/client/el9:1.0.0
RUN dnf install -y java-11-openjdk-headless jq nmap-ncat
COPY config/config-patch.json /config.json
COPY config/cluster.properties /cluster.properties
COPY config/producer.properties /producer.properties
COPY config/kaf_05/credentials.json /credentials.json
COPY rpm/kaf_06.rpm /kaf_06.rpm
RUN rpm -ivh --nodeps /kaf_06.rpm
COPY files/entrypoint.manager.sh /ipa_01.conf.d/post/entrypoint.sh
COPY jaas /jaas
